#!/bin/bash

set -eo pipefail

xcodebuild \
  -workspace QuickDocumentationExamples.xcworkspace \
  -scheme Examples \
  -sdk iphonesimulator \
  -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' \
  test | bundle exec xcpretty
