#!/bin/bash

set -e

xcodebuild \
  -project QuickDocumentationExamples.xcodeproj \
  -scheme Examples \
  -sdk iphonesimulator \
  -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' \
  test
